CREATE DATABASE IF NOT EXISTS prestacao_servicos
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE prestacao_servicos;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('CLIENTE', 'PRESTADOR', 'ADMIN') NOT NULL,
  status ENUM('ATIVO', 'BLOQUEADO') NOT NULL DEFAULT 'ATIVO',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS client_profiles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL UNIQUE,
  phone VARCHAR(30),
  city VARCHAR(90),
  state VARCHAR(2),
  address VARCHAR(180),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS provider_profiles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL UNIQUE,
  phone VARCHAR(30),
  document VARCHAR(30),
  city VARCHAR(90),
  state VARCHAR(2),
  bio TEXT,
  rating DECIMAL(3,2) NOT NULL DEFAULT 0,
  is_verified BOOLEAN NOT NULL DEFAULT FALSE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS provider_payout_accounts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  provider_id INT NOT NULL UNIQUE,
  payout_method ENUM('PIX', 'CONTA_BANCARIA') NOT NULL DEFAULT 'PIX',
  pix_key VARCHAR(160),
  bank_name VARCHAR(120),
  agency VARCHAR(20),
  account_number VARCHAR(40),
  account_type ENUM('CORRENTE', 'POUPANCA') DEFAULT 'CORRENTE',
  holder_name VARCHAR(120),
  document VARCHAR(30),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (provider_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS provider_balances (
  provider_id INT PRIMARY KEY,
  available_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
  pending_fee_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (provider_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS service_categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(90) NOT NULL UNIQUE,
  description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS services (
  id INT AUTO_INCREMENT PRIMARY KEY,
  provider_id INT NOT NULL,
  category_id INT NOT NULL,
  title VARCHAR(140) NOT NULL,
  description TEXT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  duration_minutes INT NOT NULL DEFAULT 60,
  status ENUM('ATIVO', 'PAUSADO') NOT NULL DEFAULT 'ATIVO',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (provider_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (category_id) REFERENCES service_categories(id)
);

CREATE TABLE IF NOT EXISTS plans (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(90) NOT NULL UNIQUE,
  description VARCHAR(255) NOT NULL,
  target_role ENUM('CLIENTE', 'PRESTADOR') NOT NULL DEFAULT 'PRESTADOR',
  monthly_price DECIMAL(10,2) NOT NULL DEFAULT 0,
  commission_rate DECIMAL(5,2) NOT NULL DEFAULT 12.00,
  max_services INT,
  max_requests_per_month INT,
  support_level VARCHAR(90) NOT NULL DEFAULT 'Padrao',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS provider_subscriptions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  provider_id INT NOT NULL,
  plan_id INT NOT NULL,
  status ENUM('ATIVA', 'CANCELADA', 'EXPIRADA') NOT NULL DEFAULT 'ATIVA',
  starts_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ends_at DATETIME,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (provider_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (plan_id) REFERENCES plans(id)
);

CREATE TABLE IF NOT EXISTS client_subscriptions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  client_id INT NOT NULL,
  plan_id INT NOT NULL,
  status ENUM('ATIVA', 'CANCELADA', 'EXPIRADA') NOT NULL DEFAULT 'ATIVA',
  starts_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ends_at DATETIME,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (client_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (plan_id) REFERENCES plans(id)
);

CREATE TABLE IF NOT EXISTS service_requests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  client_id INT NOT NULL,
  service_id INT NOT NULL,
  provider_id INT NOT NULL,
  scheduled_at DATETIME,
  address VARCHAR(180),
  notes TEXT,
  status ENUM('SOLICITADO', 'ACEITO', 'EM_ANDAMENTO', 'CONCLUIDO', 'CANCELADO') NOT NULL DEFAULT 'SOLICITADO',
  total_amount DECIMAL(10,2) NOT NULL,
  platform_fee DECIMAL(10,2) NOT NULL DEFAULT 0,
  provider_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (client_id) REFERENCES users(id),
  FOREIGN KEY (provider_id) REFERENCES users(id),
  FOREIGN KEY (service_id) REFERENCES services(id)
);

CREATE TABLE IF NOT EXISTS reviews (
  id INT AUTO_INCREMENT PRIMARY KEY,
  request_id INT NOT NULL UNIQUE,
  client_id INT NOT NULL,
  provider_id INT NOT NULL,
  rating INT NOT NULL,
  comment TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (request_id) REFERENCES service_requests(id) ON DELETE CASCADE,
  FOREIGN KEY (client_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (provider_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT chk_review_rating CHECK (rating BETWEEN 1 AND 5)
);

CREATE TABLE IF NOT EXISTS service_request_messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  request_id INT NOT NULL,
  sender_id INT NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (request_id) REFERENCES service_requests(id) ON DELETE CASCADE,
  FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS payments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  request_id INT NOT NULL UNIQUE,
  payer_id INT NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  method ENUM('PIX', 'CARTAO_CREDITO', 'CARTAO_DEBITO', 'DINHEIRO') NOT NULL DEFAULT 'PIX',
  status ENUM('PENDENTE', 'PAGO', 'ESTORNADO') NOT NULL DEFAULT 'PENDENTE',
  pix_code VARCHAR(80),
  pix_qr_payload TEXT,
  card_brand VARCHAR(40),
  card_last4 VARCHAR(4),
  provider_fee_status ENUM('NAO_APLICA', 'DESCONTADA', 'PENDENTE') NOT NULL DEFAULT 'NAO_APLICA',
  paid_at DATETIME,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (request_id) REFERENCES service_requests(id),
  FOREIGN KEY (payer_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS financial_transactions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  request_id INT,
  provider_id INT,
  type ENUM('ENTRADA', 'TAXA_PLATAFORMA', 'REPASSE_PRESTADOR', 'ESTORNO', 'TAXA_DINHEIRO_COBRADA', 'TAXA_DINHEIRO_PENDENTE', 'TAXA_DINHEIRO_COMPENSADA', 'SAQUE_PRESTADOR') NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  description VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (request_id) REFERENCES service_requests(id),
  FOREIGN KEY (provider_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS withdrawals (
  id INT AUTO_INCREMENT PRIMARY KEY,
  provider_id INT NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  method ENUM('PIX', 'CONTA_BANCARIA') NOT NULL DEFAULT 'PIX',
  status ENUM('SOLICITADO', 'PROCESSANDO', 'PAGO', 'RECUSADO') NOT NULL DEFAULT 'PROCESSANDO',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  paid_at DATETIME,
  FOREIGN KEY (provider_id) REFERENCES users(id) ON DELETE CASCADE
);

INSERT IGNORE INTO service_categories (id, name, description) VALUES
  (1, 'Limpeza', 'Servicos residenciais e comerciais de limpeza'),
  (2, 'Eletrica', 'Instalacoes e reparos eletricos'),
  (3, 'Encanamento', 'Reparos hidraulicos e manutencao'),
  (4, 'Beleza', 'Atendimentos esteticos e cuidados pessoais'),
  (5, 'Tecnologia', 'Suporte tecnico e configuracoes digitais');
